name: Node.js Package
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install Dependencies
      run: npm install --ignore-scripts
    - name: Test
      run: npm test
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Package Binaries
      run: npm run package
    - name: Publish Binaries
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'edit-roblox-place-*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
